- hosts: all
  become: yes
  roles:
    - common

- hosts: db
  become: yes
  roles:
    - mysql

- hosts: web
  become: yes
  roles:
    - flask

- hosts: load_balancer
  become: yes
  roles:
    - load_balancer
    - notifications
