- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: true
